Completed prep-javascript-dom-creation exercise.
sarah-you/lfz-prep-0123-code-solutions pull request #18
Opened 2023-01-21 03:20 UTC by sarah-you

![prep-javascript-creation](https://user-images.githubusercontent.com/103456134/213841406-2afbd9d9-a96a-453a-b41c-499aa493c786.png)

2023-01-21 03:21 UTC, sarah-you commented
Hi, 
Not sure why the h1 Hello World isn't showing up for me. I checked in console and it prints the Hello World there. I feel like I did something wrong in step 10. Could you let me know where I am making the mistake?

2023-01-21 19:31 UTC, Zhiwutian requested changes
make sure to reach out in slack if you have any questions!

2023-01-21 19:31 UTC, Zhiwutian commented on prep-javascript-dom-creation/index.html
> +  document.getElementsByTagName('$heading').textContent = 'Hello World!';
you don't need to query here, you can use the `$heading` variable to update the textContent

2023-01-21 20:14 UTC, sarah-you commented
![prep-javascript-dom-creation 2](https://user-images.githubusercontent.com/103456134/213885479-813dbb36-2bf1-48d2-96b5-ff4773c32632.png)

2023-01-23 17:27 UTC, Zhiwutian approved these changes
👍🏼

2023-03-22 17:52 UTC, merged